import { Home, Face3, Email, Search, ShoppingCart } from "@mui/icons-material";

//HEADER
export const APP_TITLE = "Syber's Books";
export const APP_TITLE_IMAGE_FILE_NAME = "./images/app-title.png";
export const MENU_ITEMS = [
  { title: "Home", link: "/", icon: <Home /> },
  { title: "Shop", link: "/shop", icon: <Search /> },
  { title: "About", link: "/about", icon: <Face3 /> },
  { title: "Contact", link: "/contact", icon: <Email /> },
  { title: "Cart", link: "/cart", icon: <ShoppingCart /> },
];
export const PAYMENT_ROUTES = [
  { title: "Success", link: "/success" },
  { title: "Cancel", link: "/cancel" },
];

//HOME PAGE
export const HOME = {
  hero: {
    titles: ["Rare.", "Out of Print.", "Niche."],
    description: "Melbourne's #1 Second-Hand Bookstore",
    image: "./images/home-photo.jpg",
    button: "Start Browsing",
  },
};

//ABOUT PAGE
export const ABOUT = {
  title: "About",
  description: [
    "(As all true stories start) Once upon a time there was a bookshop called Pigs' Wings Books run by a young blonde-headed girl called Jean.",
    "There was another young girl called Penny who had completed her nursing training in Queensland, and had come to the big smoke of Melbourne...",
  ],
  terms: [
    "All transactions are in Australian dollars (AUD).",
    "We accept Mastercard, Visa, Diners, Amex, and PayPal.",
  ],
  image: "./images/about-photo.png",
  button: "Shop Now",
};

//SEARCH BAR
export const SEARCH_BAR_PLACEHOLDER =
  "Type to search for a book by title, author or ISBN";

//SHOP PAGE
export const SHOP = {
  searchTitle: "Search from our collection of over 100,000 books:",
  searchResultsTitle: "Search Results",
  sortByMenuItems: [
    { label: "Price: Low to High", value: "asc" },
    { label: "Price: High to Low", value: "desc" },
  ],
  booksPerPageMenuItems: [
    { label: "12", value: 12 },
    { label: "24", value: 24 },
    { label: "48", value: 48 },
  ],
  booksPerPageLabel: "Books Per Page",
  sortByLabel: "Sort By",
  missingValuesText: {
    title: "Untitled",
    author: "Unknown author",
    price: "No price found",
    isbn: "ISBN not available",
  },
  noResults: "No results found. Try alter your search term.",
  noResultsSuggestions: [
    "Capitalise search terms to get better matches",
    "Authors are typically listed in 'Last Name, First Name' format",
  ],
  searchResultsError:
    "Error encountered while attempting to search the database. Please try again later.",
  modalTabs: {
    0: "Details",
    1: "Description",
  },
  modalButtons: {
    add: "Add To Cart",
    remove: "Remove From Cart",
  },
  addedToCartMessage: " added to cart",
  removedFromCartMessage: " removed from cart",
};

//CONTACT PAGE
export const CONTACT = {
  title: "Contact Us",
  helpText:
    "If you have any questions, comments or feedback, or you would like some assistance with your order, feel free to contact the store by phone or email (below), or just use the form.",
  storeContactDetails: [
    "Penny Merrit",
    "Syber's Books",
    "666 Glenhuntly Road",
    "Caulfield South, VIC 3162",
    { phone: "0419 330 240" },
    { email: "sybersbooks@gmail.com" },
  ],
  fields: [
    {
      id: "name",
      name: "name",
      label: "Name",
      required: true,
      error: "Please enter your name",
    },
    {
      id: "email",
      name: "email",
      label: "Email",
      required: true,
      error: "Please enter a valid email address",
    },
    {
      id: "phone",
      name: "phone",
      label: "Phone",
      required: true,
      error: "Please enter a valid phone number",
    },
    {
      id: "message",
      name: "message",
      label: "Message",
      multiline: true,
      rows: 4, // only applies if multiline is true
      required: true,
      error: "Please enter a message (1000 characters or less)",
    },
  ],
  submitButton: "Send",
  enquirySuccessMsg: "Your enquiry has been sent. Thank you!",
  googleMapsCoordinates: { lat: -37.886479, lng: 145.017559 },
  googleMapsZoom: 16,
  googleMapsMarkerTitle: "Syber's Books",
  googleMapsMarkerDescription: "666 Glenhuntly Rd, Caulfield South, VIC 3162",
};

//CART
export const CART = {
  title: "Cart",
  cartTotals: "Cart Totals",
  columnHeaders: ["", "Book Title", "Price"],
  subtotal: "Subtotal",
  shipping: "Shipping",
  shippingCostOptions: [
    { label: "Standard Shipping ($14.99 AUD)", value: 14.99 },
    { label: "Express Shipping ($29.99 AUD)", value: 29.99 },
  ],
  total: "Total",
  transactionCancelled: "TRANSACTION CANCELLED",
};

//GOOGLE PAY
export const UNSERVICEABLE_SHIPPING_COUNTRIES = [];
export const SHIPPING_ADDRESS_UNSERVICEABLE_REASON =
  "We cannot deliver to the shipping address you have provided.";
export const SHIPPING_OPTIONS = [
  {
    id: "free",
    label: "Free shipping",
    description: "Free shipping arrives in 5-7 business days",
    price: "0.00",
  },
  {
    id: "express",
    label: "Express shipping",
    description: "Express shipping delivered in 1-3 business days",
    price: "5.00",
  },
];

export const FOOTER = {
  imageAlt: "Syber's Books",
  image: "./images/app-title.png",
  copyright: "Copyright © AB Development",
  link: "https://www.facebook.com/SybersBooks/",
};

export const DISCARDED_CATEGORIES_FROM_OLD_WEBSITE = [
  "Aboriginal",
  "Academic",
  "Alternate Lifestyles",
  "Anthology",
  "Australian",
  "Best Sellers",
  "Business & Profit",
  "Canadian Studies",
  "Child Care",
  "Children's Literature",
  "Classic Tales of Other Lands",
  "Classics",
  "Contemporary Literature",
  "Cookbooks",
  "True Crime",
  "Cults",
  "Ecology & Environment",
  "Espionage",
  "Etiquette & Home Affairs",
  "French Books",
  "Fashion & Beauty",
  "Feminism",
  "Women's Issues, Film & Media",
  "Fine Arts",
  "First Editions",
  "Food & Wine",
  "Health & Wellbeing",
  "Historical Biography",
  "Ancient History",
  "Modern History",
  "Indigenous Australia",
  "Language",
  "Linguistics & Communication",
  "Literary Theory",
  "Literary Biography",
  "Modern Classics",
  "Natural History & the Animal Kingdom",
  "Ornithology",
  "Personal Development",
  "Plays",
  "Politics of Disability",
  "Popular Novels of the ealy & mid-20th Century",
  "Pregnancy & Parenting",
  "Theology & Mythology",
  "Social Commentary & World Affairs",
  "Sport & Leisure",
  "Writing & Publishing",
  "Young Adult Fiction",
];

export const CATEGORIES_FROM_OLD_WEBSITE = [
  "Antiquarian",
  "Anthropology",
  "Archaeology",
  "Architecture",
  "Art",
  "Aviation",
  "Biography",
  "Crime Fiction",
  "Economics",
  "Education",
  "Erotica",
  "Fantasy",
  "Gardening",
  "Gay & Lesbian",
  "History",
  "Humour",
  "Men's Issues",
  "Military",
  "Music",
  "New Age",
  "Philosophy",
  "Photography",
  "Poetry",
  "Psychology",
  "Reference",
  "Religion",
  "Science & Technology",
  "Science Fiction",
  "Travel",
];

export const CATEGORIES_FROM_DB = [
  "Animals & Birds",
  "Anthropology",
  "Antiquarian & Rare",
  "Antiques & Collectibles",
  "Archaeology",
  "Architecture",
  "Architecture ",
  "Arctic & Antarctic",
  "Art",
  "Art & Design",
  "Art -- Pottery",
  "Art -- Primitive",
  "Astronomy",
  "Autobiography",
  "Automobiles & Vehicles",
  "Aviation",
  "Biography & Autobiography",
  "Biography -- Arts",
  "Biography -- Military",
  "Books about Books",
  "Books for Writers",
  "Books on Books",
  "Books on books",
  "Business, Finance & Marketing",
  "Charlottesville, Virginia",
  "Children",
  "Children ",
  "Comics & Graphic Novels",
  "Communications & Media",
  "Computers & Internet",
  "Cooking -- Desserts",
  "Cooking -- India",
  "Cooking -- Vegetarian",
  "Cooking, Wine & Dining",
  "Crafts & Hobbies",
  "Crim961",
  "Crime Fiction",
  "Current Affairs",
  "Dance",
  "Diaries",
  "Dictionary",
  "Economics",
  "Education",
  "Education ",
  "Engineering, Industrial & Trades",
  "Engineering, Industrial, Trade",
  "Environment & Ecology",
  "Erotica",
  "Essays & Literary Criticism",
  "Exploration",
  "Facsimile",
  "Family",
  "Family & Relationships",
  "Fantasy fiction",
  "Farming & Rural Life",
  "Fashion, Fabrics & Style",
  "Fiction",
  "Fiction -- Adventure ",
  "Film, Radio & Television",
  "Film, Radio & Television  ",
  "Fishing & Hunting",
  "Games & Gaming",
  "Gardening",
  "Gay & Lesbian",
  "Genealogy & Local History",
  "Geography & Maps",
  "Geology",
  "Groups, Clubs & Associations",
  "History",
  "History ",
  "History -- America",
  "History -- Asia",
  "History -- Britain",
  "History -- France",
  "Hobbies",
  "Hobbies -- Handcrafts",
  "Hobbies -- Stamps",
  "Holidays & Special Occasions",
  "Holocaust",
  "Home Decorating & Repair",
  "Horror",
  "Humour",
  "Humour ",
  "Illustrated",
  "Illustrated -- Childrens Books",
  "Indigenous Cultures",
  "Interior Design",
  "Journalism",
  "Judaica",
  "Judaism",
  "Language & Linguistics",
  "Law & Criminal Studies",
  "LiX",
  "Limited-Edition",
  "Literature",
  "Literature & Literary",
  "Local History -- Australia",
  "Local History -- Queensland",
  "Local History -- Western Australia",
  "Magic, Paranormal & Occult",
  "Management",
  "Mathematics",
  "Medicine & Health",
  "Military & Warfare",
  "Military History -- Aviation",
  "Military History -- World War II",
  "Mining",
  "Mountain View, California",
  "Mountaineering",
  "Music",
  "Mythology",
  "Myths, Legends & Folklore",
  "Natural History & Resources",
  "Natural History -- Birds",
  "Natural History -- Botany",
  "Natural History -- Zoology",
  "New Age & Alternative",
  "Parenting & Childcare",
  "Philosophy",
  "Philosophy ",
  "Photography",
  "Poetry",
  "Poetry ",
  "Politics",
  "Politics & Government",
  "Politics & Government  ",
  "Psychology & Psychiatry",
  "Railways",
  "Reference",
  "Religion & Theology",
  "Romance",
  "Royalty",
  "Science",
  "Science & Technology",
  "Science Fiction & Fantasy",
  "Science and Technology",
  "Sculpture & Ceramics",
  "Section",
  "Self Help & Motivation",
  "Self-Help",
  "Sexuality & Gender",
  "Ships & the Sea",
  "Signed",
  "Social History",
  "Sociology & Culture",
  "Sports & Pastimes",
  "TV Tie-in",
  "Tapestry",
  "Teens & Young Adult",
  "Theatre & Plays",
  "Today Too Many",
  "Transport",
  "Travel & Places",
  "True Crime",
  "Wine",
  "Women & Feminism",
  "You Can",
  "architecture",
  "business, Finance & Marketing",
  "children",
  "education",
  "fiction",
  "history",
  "humour",
  "mathematics",
  "music",
  "philosophy",
  "photography",
  "poetry",
  "reference",
];

export const CATEGORIES = "Browse By Categories";
